// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// JSONResponse carries a descriptor.Envelope as raw JSON in `payload`. Used
// for Manifest (and any future RPC whose response shape is intentionally
// schemaless).
type JSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONResponse) Reset() {
	*x = JSONResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONResponse) ProtoMessage() {}

func (x *JSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONResponse.ProtoReflect.Descriptor instead.
func (*JSONResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *JSONResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OpenPublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPublicRequest) Reset() {
	*x = OpenPublicRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPublicRequest) ProtoMessage() {}

func (x *OpenPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPublicRequest.ProtoReflect.Descriptor instead.
func (*OpenPublicRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *OpenPublicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenPublicRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreatePrivateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TtlSeconds int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Subject (sub claim) baked into the issued access + refresh tokens.
	// Empty means anonymous.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Scopes is the optional pattern-grant set baked into both tokens.
	// Each scope binds a channel-name pattern (e.g. private:webapp.user.42.*)
	// to a list of verbs (subscribe, publish, manage). Empty produces a
	// token whose only authorization is the chs exact-match on `name`.
	// Patterns are validated against the channel grammar at issue time;
	// cross-visibility patterns (*:foo.bar) are rejected with
	// PARSEC_INVALID_ARGUMENT.
	Scopes        []*Scope `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrivateRequest) Reset() {
	*x = CreatePrivateRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateRequest) ProtoMessage() {}

func (x *CreatePrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePrivateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePrivateRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreatePrivateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePrivateRequest) GetScopes() []*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// Scope is one entry in CreatePrivateRequest.scopes.
type Scope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern is the channel-name pattern, e.g. `private:webapp.user.42.*`.
	// Single-star matches one segment, double-star matches one-or-more
	// trailing segments (last position only).
	Pattern string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Verbs is the set of granted actions. Allowed values:
	// "subscribe", "publish", "manage".
	Verbs []string `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// Deny inverts the scope: when true, a matching (channel, verb) pair is
	// subtracted from the grant set with "deny wins" precedence. A scope
	// with deny=true on a pattern that overlaps an allow scope still wins
	// — denies are not unlocked by any allow. A deny scope without an
	// overlapping allow is a defensive no-op. The default (false) means a
	// plain allow scope.
	Deny          bool `protobuf:"varint,3,opt,name=deny,proto3" json:"deny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *Scope) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Scope) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *Scope) GetDeny() bool {
	if x != nil {
		return x.Deny
	}
	return false
}

type ChannelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRef) Reset() {
	*x = ChannelRef{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRef) ProtoMessage() {}

func (x *ChannelRef) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRef.ProtoReflect.Descriptor instead.
func (*ChannelRef) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChannelSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // open | closed | deleted
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // RFC3339
	LastActive    string                 `protobuf:"bytes,5,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSummary) Reset() {
	*x = ChannelSummary{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSummary) ProtoMessage() {}

func (x *ChannelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSummary.ProtoReflect.Descriptor instead.
func (*ChannelSummary) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChannelSummary) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ChannelSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChannelSummary) GetLastActive() string {
	if x != nil {
		return x.LastActive
	}
	return ""
}

type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *ChannelSummary        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelResponse) GetChannel() *ChannelSummary {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelSummary      `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListChannelsResponse) GetChannels() []*ChannelSummary {
	if x != nil {
		return x.Channels
	}
	return nil
}

// Credentials is the one-shot private-channel token pair, returned by
// CreatePrivate. The access + refresh tokens are returned exactly once.
type Credentials struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccessToken        string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken       string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresUnix  int64                  `protobuf:"varint,4,opt,name=access_expires_unix,json=accessExpiresUnix,proto3" json:"access_expires_unix,omitempty"`
	RefreshExpiresUnix int64                  `protobuf:"varint,5,opt,name=refresh_expires_unix,json=refreshExpiresUnix,proto3" json:"refresh_expires_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *Credentials) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Credentials) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Credentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Credentials) GetAccessExpiresUnix() int64 {
	if x != nil {
		return x.AccessExpiresUnix
	}
	return 0
}

func (x *Credentials) GetRefreshExpiresUnix() int64 {
	if x != nil {
		return x.RefreshExpiresUnix
	}
	return 0
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *PublishRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Epoch         string                 `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *PublishResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishResponse) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

type PresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribers   int32                  `protobuf:"varint,1,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *PresenceResponse) GetSubscribers() int32 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

// RefreshTokenRequest exchanges a refresh token for an access token.
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RefreshTokenResponse carries the new access token + its expiry. When
// the redeemed refresh carried a rotation JTI the server also returns a
// fresh refresh in the same family; legacy callers may ignore the
// rotation fields, but a client that does ignore them will fail on the
// next redemption because the JTI is now marked redeemed server-side.
type RefreshTokenResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessExpiresUnix  int64                  `protobuf:"varint,2,opt,name=access_expires_unix,json=accessExpiresUnix,proto3" json:"access_expires_unix,omitempty"`
	RefreshToken       string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshExpiresUnix int64                  `protobuf:"varint,4,opt,name=refresh_expires_unix,json=refreshExpiresUnix,proto3" json:"refresh_expires_unix,omitempty"`
	Rotated            bool                   `protobuf:"varint,5,opt,name=rotated,proto3" json:"rotated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessExpiresUnix() int64 {
	if x != nil {
		return x.AccessExpiresUnix
	}
	return 0
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshExpiresUnix() int64 {
	if x != nil {
		return x.RefreshExpiresUnix
	}
	return 0
}

func (x *RefreshTokenResponse) GetRotated() bool {
	if x != nil {
		return x.Rotated
	}
	return false
}

// IssueMgmtRequest mints a new mgmt bearer signed by the currently active
// key. Used during key rotation so operators don't get locked out when
// they retire the key that signed their current bearer.
type IssueMgmtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMgmtRequest) Reset() {
	*x = IssueMgmtRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMgmtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMgmtRequest) ProtoMessage() {}

func (x *IssueMgmtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMgmtRequest.ProtoReflect.Descriptor instead.
func (*IssueMgmtRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *IssueMgmtRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueMgmtRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// IssueMgmtResponse carries the fresh mgmt token and its expiry.
type IssueMgmtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MgmtToken     string                 `protobuf:"bytes,1,opt,name=mgmt_token,json=mgmtToken,proto3" json:"mgmt_token,omitempty"`
	ExpiresUnix   int64                  `protobuf:"varint,2,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	SignedByKeyId string                 `protobuf:"bytes,3,opt,name=signed_by_key_id,json=signedByKeyId,proto3" json:"signed_by_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMgmtResponse) Reset() {
	*x = IssueMgmtResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMgmtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMgmtResponse) ProtoMessage() {}

func (x *IssueMgmtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMgmtResponse.ProtoReflect.Descriptor instead.
func (*IssueMgmtResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *IssueMgmtResponse) GetMgmtToken() string {
	if x != nil {
		return x.MgmtToken
	}
	return ""
}

func (x *IssueMgmtResponse) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *IssueMgmtResponse) GetSignedByKeyId() string {
	if x != nil {
		return x.SignedByKeyId
	}
	return ""
}

// KeySummary is the wire shape of one ring key.
type KeySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                            // active | verify-only | retired
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	RetiredAt     string                 `protobuf:"bytes,4,opt,name=retired_at,json=retiredAt,proto3" json:"retired_at,omitempty"` // RFC3339, empty when not retired
	Alg           string                 `protobuf:"bytes,5,opt,name=alg,proto3" json:"alg,omitempty"`                              // HS256 (default) | RS256 | EdDSA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySummary) Reset() {
	*x = KeySummary{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySummary) ProtoMessage() {}

func (x *KeySummary) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySummary.ProtoReflect.Descriptor instead.
func (*KeySummary) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *KeySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeySummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *KeySummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KeySummary) GetRetiredAt() string {
	if x != nil {
		return x.RetiredAt
	}
	return ""
}

func (x *KeySummary) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

// GenerateKeyRequest selects the algorithm for the new key.
type GenerateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alg           string                 `protobuf:"bytes,1,opt,name=alg,proto3" json:"alg,omitempty"` // HS256 (default) | RS256 | EdDSA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateKeyRequest) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

// ListKeysResponse is the bulk listing for the ring.
type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveKeyId   string                 `protobuf:"bytes,1,opt,name=active_key_id,json=activeKeyId,proto3" json:"active_key_id,omitempty"`
	Keys          []*KeySummary          `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListKeysResponse) GetActiveKeyId() string {
	if x != nil {
		return x.ActiveKeyId
	}
	return ""
}

func (x *ListKeysResponse) GetKeys() []*KeySummary {
	if x != nil {
		return x.Keys
	}
	return nil
}

// KeyRef identifies one key by id.
type KeyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRef) Reset() {
	*x = KeyRef{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRef) ProtoMessage() {}

func (x *KeyRef) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRef.ProtoReflect.Descriptor instead.
func (*KeyRef) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *KeyRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DlqItem is the wire shape of a dead-letter queue entry. Recipient is
// transported as a JSON blob because each sink defines its own concrete
// type; consumers that need the typed Recipient can parse it sink-side.
type DlqItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sink          string                 `protobuf:"bytes,2,opt,name=sink,proto3" json:"sink,omitempty"`
	At            string                 `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`               // RFC3339Nano
	Recipient     []byte                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"` // JSON
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attempts      int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqItem) Reset() {
	*x = DlqItem{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqItem) ProtoMessage() {}

func (x *DlqItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqItem.ProtoReflect.Descriptor instead.
func (*DlqItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *DlqItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DlqItem) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

func (x *DlqItem) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *DlqItem) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *DlqItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DlqItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DlqItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DlqItem) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DlqItem) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type DlqListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sink          string                 `protobuf:"bytes,1,opt,name=sink,proto3" json:"sink,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqListRequest) Reset() {
	*x = DlqListRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqListRequest) ProtoMessage() {}

func (x *DlqListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqListRequest.ProtoReflect.Descriptor instead.
func (*DlqListRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *DlqListRequest) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

func (x *DlqListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DlqListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DlqItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqListResponse) Reset() {
	*x = DlqListResponse{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqListResponse) ProtoMessage() {}

func (x *DlqListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqListResponse.ProtoReflect.Descriptor instead.
func (*DlqListResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *DlqListResponse) GetItems() []*DlqItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DlqCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sink          string                 `protobuf:"bytes,1,opt,name=sink,proto3" json:"sink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqCountRequest) Reset() {
	*x = DlqCountRequest{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqCountRequest) ProtoMessage() {}

func (x *DlqCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqCountRequest.ProtoReflect.Descriptor instead.
func (*DlqCountRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *DlqCountRequest) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

type DlqCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqCountResponse) Reset() {
	*x = DlqCountResponse{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqCountResponse) ProtoMessage() {}

func (x *DlqCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqCountResponse.ProtoReflect.Descriptor instead.
func (*DlqCountResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *DlqCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DlqDiscardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqDiscardRequest) Reset() {
	*x = DlqDiscardRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqDiscardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqDiscardRequest) ProtoMessage() {}

func (x *DlqDiscardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqDiscardRequest.ProtoReflect.Descriptor instead.
func (*DlqDiscardRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *DlqDiscardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DlqReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqReplayRequest) Reset() {
	*x = DlqReplayRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqReplayRequest) ProtoMessage() {}

func (x *DlqReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqReplayRequest.ProtoReflect.Descriptor instead.
func (*DlqReplayRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *DlqReplayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RevokeTokenRequest marks a single token (by jti) as revoked. The
// optional user_id and reason are recorded with the entry for audit
// purposes; revocation matches on token_id regardless.
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *RevokeTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RevokeTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeUserRequest invalidates every token previously issued to
// user_id. Tokens issued AFTER the call land outside the cutoff and
// remain valid. The optional reason is recorded for audit.
type RevokeUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserRequest) Reset() {
	*x = RevokeUserRequest{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserRequest) ProtoMessage() {}

func (x *RevokeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *RevokeUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x06parsec\"\a\n" +
	"\x05Empty\"(\n" +
	"\fJSONResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"H\n" +
	"\x11OpenPublicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"\x8c\x01\n" +
	"\x14CreatePrivateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12%\n" +
	"\x06scopes\x18\x04 \x03(\v2\r.parsec.ScopeR\x06scopes\"K\n" +
	"\x05Scope\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05verbs\x18\x02 \x03(\tR\x05verbs\x12\x12\n" +
	"\x04deny\x18\x03 \x01(\bR\x04deny\" \n" +
	"\n" +
	"ChannelRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9b\x01\n" +
	"\x0eChannelSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vlast_active\x18\x05 \x01(\tR\n" +
	"lastActive\"C\n" +
	"\x0fChannelResponse\x120\n" +
	"\achannel\x18\x01 \x01(\v2\x16.parsec.ChannelSummaryR\achannel\"J\n" +
	"\x14ListChannelsResponse\x122\n" +
	"\bchannels\x18\x01 \x03(\v2\x16.parsec.ChannelSummaryR\bchannels\"\xcb\x01\n" +
	"\vCredentials\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12.\n" +
	"\x13access_expires_unix\x18\x04 \x01(\x03R\x11accessExpiresUnix\x120\n" +
	"\x14refresh_expires_unix\x18\x05 \x01(\x03R\x12refreshExpiresUnix\"8\n" +
	"\x0ePublishRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"?\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\"4\n" +
	"\x10PresenceResponse\x12 \n" +
	"\vsubscribers\x18\x01 \x01(\x05R\vsubscribers\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xda\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\x13access_expires_unix\x18\x02 \x01(\x03R\x11accessExpiresUnix\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x120\n" +
	"\x14refresh_expires_unix\x18\x04 \x01(\x03R\x12refreshExpiresUnix\x12\x18\n" +
	"\arotated\x18\x05 \x01(\bR\arotated\"M\n" +
	"\x10IssueMgmtRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"~\n" +
	"\x11IssueMgmtResponse\x12\x1d\n" +
	"\n" +
	"mgmt_token\x18\x01 \x01(\tR\tmgmtToken\x12!\n" +
	"\fexpires_unix\x18\x02 \x01(\x03R\vexpiresUnix\x12'\n" +
	"\x10signed_by_key_id\x18\x03 \x01(\tR\rsignedByKeyId\"\x80\x01\n" +
	"\n" +
	"KeySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"retired_at\x18\x04 \x01(\tR\tretiredAt\x12\x10\n" +
	"\x03alg\x18\x05 \x01(\tR\x03alg\"&\n" +
	"\x12GenerateKeyRequest\x12\x10\n" +
	"\x03alg\x18\x01 \x01(\tR\x03alg\"^\n" +
	"\x10ListKeysResponse\x12\"\n" +
	"\ractive_key_id\x18\x01 \x01(\tR\vactiveKeyId\x12&\n" +
	"\x04keys\x18\x02 \x03(\v2\x12.parsec.KeySummaryR\x04keys\"\x18\n" +
	"\x06KeyRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbc\x02\n" +
	"\aDlqItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04sink\x18\x02 \x01(\tR\x04sink\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\tR\x02at\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\fR\trecipient\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x129\n" +
	"\bmetadata\x18\a \x03(\v2\x1d.parsec.DlqItem.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0eDlqListRequest\x12\x12\n" +
	"\x04sink\x18\x01 \x01(\tR\x04sink\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"8\n" +
	"\x0fDlqListResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.parsec.DlqItemR\x05items\"%\n" +
	"\x0fDlqCountRequest\x12\x12\n" +
	"\x04sink\x18\x01 \x01(\tR\x04sink\"(\n" +
	"\x10DlqCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"#\n" +
	"\x11DlqDiscardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10DlqReplayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x12RevokeTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"D\n" +
	"\x11RevokeUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xc9\t\n" +
	"\rParsecService\x12/\n" +
	"\bManifest\x12\r.parsec.Empty\x1a\x14.parsec.JSONResponse\x12@\n" +
	"\n" +
	"OpenPublic\x12\x19.parsec.OpenPublicRequest\x1a\x17.parsec.ChannelResponse\x12B\n" +
	"\rCreatePrivate\x12\x1c.parsec.CreatePrivateRequest\x1a\x13.parsec.Credentials\x12;\n" +
	"\fListChannels\x12\r.parsec.Empty\x1a\x1c.parsec.ListChannelsResponse\x129\n" +
	"\n" +
	"GetChannel\x12\x12.parsec.ChannelRef\x1a\x17.parsec.ChannelResponse\x122\n" +
	"\rDeleteChannel\x12\x12.parsec.ChannelRef\x1a\r.parsec.Empty\x12:\n" +
	"\aPublish\x12\x16.parsec.PublishRequest\x1a\x17.parsec.PublishResponse\x128\n" +
	"\bPresence\x12\x12.parsec.ChannelRef\x1a\x18.parsec.PresenceResponse\x12I\n" +
	"\fRefreshToken\x12\x1b.parsec.RefreshTokenRequest\x1a\x1c.parsec.RefreshTokenResponse\x12@\n" +
	"\tIssueMgmt\x12\x18.parsec.IssueMgmtRequest\x1a\x19.parsec.IssueMgmtResponse\x123\n" +
	"\bListKeys\x12\r.parsec.Empty\x1a\x18.parsec.ListKeysResponse\x12=\n" +
	"\vGenerateKey\x12\x1a.parsec.GenerateKeyRequest\x1a\x12.parsec.KeySummary\x12+\n" +
	"\n" +
	"PromoteKey\x12\x0e.parsec.KeyRef\x1a\r.parsec.Empty\x12*\n" +
	"\tRetireKey\x12\x0e.parsec.KeyRef\x1a\r.parsec.Empty\x12*\n" +
	"\n" +
	"ReloadKeys\x12\r.parsec.Empty\x1a\r.parsec.Empty\x12:\n" +
	"\aDlqList\x12\x16.parsec.DlqListRequest\x1a\x17.parsec.DlqListResponse\x12=\n" +
	"\bDlqCount\x12\x17.parsec.DlqCountRequest\x1a\x18.parsec.DlqCountResponse\x126\n" +
	"\n" +
	"DlqDiscard\x12\x19.parsec.DlqDiscardRequest\x1a\r.parsec.Empty\x124\n" +
	"\tDlqReplay\x12\x18.parsec.DlqReplayRequest\x1a\r.parsec.Empty\x128\n" +
	"\vRevokeToken\x12\x1a.parsec.RevokeTokenRequest\x1a\r.parsec.Empty\x126\n" +
	"\n" +
	"RevokeUser\x12\x19.parsec.RevokeUserRequest\x1a\r.parsec.EmptyB'Z%github.com/frankbardon/parsec/rpc;rpcb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_service_proto_goTypes = []any{
	(*Empty)(nil),                // 0: parsec.Empty
	(*JSONResponse)(nil),         // 1: parsec.JSONResponse
	(*OpenPublicRequest)(nil),    // 2: parsec.OpenPublicRequest
	(*CreatePrivateRequest)(nil), // 3: parsec.CreatePrivateRequest
	(*Scope)(nil),                // 4: parsec.Scope
	(*ChannelRef)(nil),           // 5: parsec.ChannelRef
	(*ChannelSummary)(nil),       // 6: parsec.ChannelSummary
	(*ChannelResponse)(nil),      // 7: parsec.ChannelResponse
	(*ListChannelsResponse)(nil), // 8: parsec.ListChannelsResponse
	(*Credentials)(nil),          // 9: parsec.Credentials
	(*PublishRequest)(nil),       // 10: parsec.PublishRequest
	(*PublishResponse)(nil),      // 11: parsec.PublishResponse
	(*PresenceResponse)(nil),     // 12: parsec.PresenceResponse
	(*RefreshTokenRequest)(nil),  // 13: parsec.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 14: parsec.RefreshTokenResponse
	(*IssueMgmtRequest)(nil),     // 15: parsec.IssueMgmtRequest
	(*IssueMgmtResponse)(nil),    // 16: parsec.IssueMgmtResponse
	(*KeySummary)(nil),           // 17: parsec.KeySummary
	(*GenerateKeyRequest)(nil),   // 18: parsec.GenerateKeyRequest
	(*ListKeysResponse)(nil),     // 19: parsec.ListKeysResponse
	(*KeyRef)(nil),               // 20: parsec.KeyRef
	(*DlqItem)(nil),              // 21: parsec.DlqItem
	(*DlqListRequest)(nil),       // 22: parsec.DlqListRequest
	(*DlqListResponse)(nil),      // 23: parsec.DlqListResponse
	(*DlqCountRequest)(nil),      // 24: parsec.DlqCountRequest
	(*DlqCountResponse)(nil),     // 25: parsec.DlqCountResponse
	(*DlqDiscardRequest)(nil),    // 26: parsec.DlqDiscardRequest
	(*DlqReplayRequest)(nil),     // 27: parsec.DlqReplayRequest
	(*RevokeTokenRequest)(nil),   // 28: parsec.RevokeTokenRequest
	(*RevokeUserRequest)(nil),    // 29: parsec.RevokeUserRequest
	nil,                          // 30: parsec.DlqItem.MetadataEntry
}
var file_service_proto_depIdxs = []int32{
	4,  // 0: parsec.CreatePrivateRequest.scopes:type_name -> parsec.Scope
	6,  // 1: parsec.ChannelResponse.channel:type_name -> parsec.ChannelSummary
	6,  // 2: parsec.ListChannelsResponse.channels:type_name -> parsec.ChannelSummary
	17, // 3: parsec.ListKeysResponse.keys:type_name -> parsec.KeySummary
	30, // 4: parsec.DlqItem.metadata:type_name -> parsec.DlqItem.MetadataEntry
	21, // 5: parsec.DlqListResponse.items:type_name -> parsec.DlqItem
	0,  // 6: parsec.ParsecService.Manifest:input_type -> parsec.Empty
	2,  // 7: parsec.ParsecService.OpenPublic:input_type -> parsec.OpenPublicRequest
	3,  // 8: parsec.ParsecService.CreatePrivate:input_type -> parsec.CreatePrivateRequest
	0,  // 9: parsec.ParsecService.ListChannels:input_type -> parsec.Empty
	5,  // 10: parsec.ParsecService.GetChannel:input_type -> parsec.ChannelRef
	5,  // 11: parsec.ParsecService.DeleteChannel:input_type -> parsec.ChannelRef
	10, // 12: parsec.ParsecService.Publish:input_type -> parsec.PublishRequest
	5,  // 13: parsec.ParsecService.Presence:input_type -> parsec.ChannelRef
	13, // 14: parsec.ParsecService.RefreshToken:input_type -> parsec.RefreshTokenRequest
	15, // 15: parsec.ParsecService.IssueMgmt:input_type -> parsec.IssueMgmtRequest
	0,  // 16: parsec.ParsecService.ListKeys:input_type -> parsec.Empty
	18, // 17: parsec.ParsecService.GenerateKey:input_type -> parsec.GenerateKeyRequest
	20, // 18: parsec.ParsecService.PromoteKey:input_type -> parsec.KeyRef
	20, // 19: parsec.ParsecService.RetireKey:input_type -> parsec.KeyRef
	0,  // 20: parsec.ParsecService.ReloadKeys:input_type -> parsec.Empty
	22, // 21: parsec.ParsecService.DlqList:input_type -> parsec.DlqListRequest
	24, // 22: parsec.ParsecService.DlqCount:input_type -> parsec.DlqCountRequest
	26, // 23: parsec.ParsecService.DlqDiscard:input_type -> parsec.DlqDiscardRequest
	27, // 24: parsec.ParsecService.DlqReplay:input_type -> parsec.DlqReplayRequest
	28, // 25: parsec.ParsecService.RevokeToken:input_type -> parsec.RevokeTokenRequest
	29, // 26: parsec.ParsecService.RevokeUser:input_type -> parsec.RevokeUserRequest
	1,  // 27: parsec.ParsecService.Manifest:output_type -> parsec.JSONResponse
	7,  // 28: parsec.ParsecService.OpenPublic:output_type -> parsec.ChannelResponse
	9,  // 29: parsec.ParsecService.CreatePrivate:output_type -> parsec.Credentials
	8,  // 30: parsec.ParsecService.ListChannels:output_type -> parsec.ListChannelsResponse
	7,  // 31: parsec.ParsecService.GetChannel:output_type -> parsec.ChannelResponse
	0,  // 32: parsec.ParsecService.DeleteChannel:output_type -> parsec.Empty
	11, // 33: parsec.ParsecService.Publish:output_type -> parsec.PublishResponse
	12, // 34: parsec.ParsecService.Presence:output_type -> parsec.PresenceResponse
	14, // 35: parsec.ParsecService.RefreshToken:output_type -> parsec.RefreshTokenResponse
	16, // 36: parsec.ParsecService.IssueMgmt:output_type -> parsec.IssueMgmtResponse
	19, // 37: parsec.ParsecService.ListKeys:output_type -> parsec.ListKeysResponse
	17, // 38: parsec.ParsecService.GenerateKey:output_type -> parsec.KeySummary
	0,  // 39: parsec.ParsecService.PromoteKey:output_type -> parsec.Empty
	0,  // 40: parsec.ParsecService.RetireKey:output_type -> parsec.Empty
	0,  // 41: parsec.ParsecService.ReloadKeys:output_type -> parsec.Empty
	23, // 42: parsec.ParsecService.DlqList:output_type -> parsec.DlqListResponse
	25, // 43: parsec.ParsecService.DlqCount:output_type -> parsec.DlqCountResponse
	0,  // 44: parsec.ParsecService.DlqDiscard:output_type -> parsec.Empty
	0,  // 45: parsec.ParsecService.DlqReplay:output_type -> parsec.Empty
	0,  // 46: parsec.ParsecService.RevokeToken:output_type -> parsec.Empty
	0,  // 47: parsec.ParsecService.RevokeUser:output_type -> parsec.Empty
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
