// Code generated by parsec-gen. DO NOT EDIT.

package parsecgen

import (
	"encoding/json"
	"strings"
)

// BrandsMeridianReportsPattern is the registered channel pattern.
const BrandsMeridianReportsPattern = "brands:meridian.reports"

// BrandsMeridianReportsSummary is the payload for the "summary" aspect on BrandsMeridianReports.
type BrandsMeridianReportsSummary string

// EventsPattern is the registered channel pattern.
const EventsPattern = "events.**"

// EventsChannel builds a concrete channel name from events.**.
func EventsChannel(rest ...string) string {
	return "events." + strings.Join(rest, ".")
}

// EventsRaw is the payload for the "raw" aspect on Events.
type EventsRaw = json.RawMessage

// SessionsPattern is the registered channel pattern.
const SessionsPattern = "sessions:{id}"

// SessionsChannel builds a concrete channel name from sessions:{id}.
func SessionsChannel(id string) string {
	return "sessions:" + id
}

// SessionsCursor is the payload for the "cursor" aspect on Sessions.
type SessionsCursor struct {
	Position int64  `json:"position"`
	UserID   string `json:"user_id"`
}

// SessionsData is the payload for the "data" aspect on Sessions.
// primary content updates
type SessionsData struct {
	Meta *struct {
		Score  float64 `json:"score,omitempty"`
		Source string  `json:"source,omitempty"`
	} `json:"meta,omitempty"`
	Tags []string `json:"tags,omitempty"`
	// rendered message
	Text   string `json:"text"`
	Tokens int64  `json:"tokens,omitempty"`
}
