// Code generated by parsec-gen. DO NOT EDIT.

/** Registered channel pattern. */
export const BrandsMeridianReportsPattern = "brands:meridian.reports" as const;

/** Payload for the "summary" aspect on BrandsMeridianReports. */
export type BrandsMeridianReportsSummary = string;

/** Registered channel pattern. */
export const EventsPattern = "events.**" as const;

/** Build a concrete channel name from events.**. */
export function eventsChannel(rest: string[]): string {
  return "events." + rest.join(".");
}

/** Payload for the "raw" aspect on Events. */
export type EventsRaw = unknown;

/** Registered channel pattern. */
export const SessionsPattern = "sessions:{id}" as const;

/** Build a concrete channel name from sessions:{id}. */
export function sessionsChannel(id: string): string {
  return "sessions:" + id;
}

/** Payload for the "cursor" aspect on Sessions. */
export interface SessionsCursor {
  position: number;
  user_id: string;
}

/** primary content updates */
export interface SessionsData {
  meta?: {
    score?: number;
    source?: string;
  };
  tags?: string[];
  /** rendered message */
  text: string;
  tokens?: number;
}

