package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/frankbardon/parsec/schema"
)

// GoGenerator emits a single self-contained Go file.
type GoGenerator struct{}

// Name implements Generator.
func (GoGenerator) Name() string { return "go" }

// Generate implements Generator. The output is gofmt'd; if the buffer
// fails to parse, the unformatted bytes are returned together with the
// format error so callers can diagnose template bugs.
func (g GoGenerator) Generate(snap schema.Snapshot, opts Options) ([]byte, error) {
	var buf bytes.Buffer

	if opts.Header != "" {
		buf.WriteString(opts.Header)
		if !strings.HasSuffix(opts.Header, "\n") {
			buf.WriteByte('\n')
		}
	}
	fmt.Fprintln(&buf, "// Code generated by parsec-gen. DO NOT EDIT.")
	fmt.Fprintln(&buf, "")
	fmt.Fprintf(&buf, "package %s\n\n", opts.pkg())

	// Whether we needed an import. Track here so we only emit the line
	// when the body actually references the package.
	imports := map[string]struct{}{}

	bodies := make([]string, 0, len(snap.Patterns))
	for _, p := range sortedPatterns(snap) {
		body, used := emitGoPattern(p)
		for k := range used {
			imports[k] = struct{}{}
		}
		bodies = append(bodies, body)
	}

	if len(imports) > 0 {
		buf.WriteString("import (\n")
		keys := make([]string, 0, len(imports))
		for k := range imports {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&buf, "\t%q\n", k)
		}
		buf.WriteString(")\n\n")
	}

	for _, body := range bodies {
		buf.WriteString(body)
	}

	out := buf.Bytes()
	formatted, err := format.Source(out)
	if err != nil {
		return out, fmt.Errorf("codegen: gofmt: %w", err)
	}
	return formatted, nil
}

// emitGoPattern returns the Go source covering one ChannelPattern: a
// pattern-string constant, an optional channel-helper function, and a
// payload struct per declared aspect.
func emitGoPattern(p schema.ChannelPattern) (string, map[string]struct{}) {
	imports := map[string]struct{}{}
	var b strings.Builder

	base := patternIdent(p.Pattern)
	fmt.Fprintf(&b, "// %sPattern is the registered channel pattern.\n", base)
	fmt.Fprintf(&b, "const %sPattern = %q\n\n", base, p.Pattern)

	placeholders := patternPlaceholders(p.Pattern)
	if len(placeholders) > 0 {
		emitGoChannelHelper(&b, base, p.Pattern, placeholders)
		// Trailing-segment placeholders use strings.Join.
		for _, ph := range placeholders {
			if ph.Trailing {
				imports["strings"] = struct{}{}
				break
			}
		}
	}

	for _, aspectName := range sortedAspectNames(p.Aspects) {
		aspect := p.Aspects[aspectName]
		emitGoAspectPayload(&b, base, aspect, imports)
	}
	return b.String(), imports
}

func emitGoChannelHelper(b *strings.Builder, base, pattern string, phs []placeholder) {
	args := make([]string, 0, len(phs))
	for _, ph := range phs {
		if ph.Trailing {
			args = append(args, ph.Name+" ...string")
			continue
		}
		args = append(args, ph.Name+" string")
	}

	fmt.Fprintf(b, "// %sChannel builds a concrete channel name from %s.\n", base, pattern)
	fmt.Fprintf(b, "func %sChannel(%s) string {\n", base, strings.Join(args, ", "))
	expr := goChannelExpr(pattern)
	fmt.Fprintf(b, "\treturn %s\n", expr)
	b.WriteString("}\n\n")
}

// goChannelExpr renders the pattern into a Go expression that
// reconstructs the channel string from the helper arguments. Trailing
// '**' placeholders become `strings.Join(rest, ".")` with a leading dot
// when there is preceding text.
func goChannelExpr(pattern string) string {
	toks := patternTokens(pattern)
	parts := make([]string, 0, len(toks))
	for i, t := range toks {
		switch {
		case t.Literal != "":
			parts = append(parts, fmt.Sprintf("%q", t.Literal))
		case t.PlaceholderName == "rest":
			// `**` — join the variadic with '.'. Prepend a '.' only
			// when there's preceding text (i.e. it's not the first
			// token). The caller is expected to pass at least one
			// element per the pattern grammar; an empty rest yields
			// just the prior literal.
			if i == 0 {
				parts = append(parts, `strings.Join(rest, ".")`)
			} else {
				parts = append(parts, `strings.Join(rest, ".")`)
			}
		default:
			parts = append(parts, t.PlaceholderName)
		}
	}
	if len(parts) == 0 {
		return `""`
	}
	return strings.Join(parts, " + ")
}

func emitGoAspectPayload(b *strings.Builder, base string, aspect schema.Aspect, imports map[string]struct{}) {
	typeName := base + aspectIdent(aspect.Name)
	if aspect.Description != "" {
		fmt.Fprintf(b, "// %s is the payload for the %q aspect on %s.\n", typeName, aspect.Name, base)
		fmt.Fprintf(b, "// %s\n", aspect.Description)
	} else {
		fmt.Fprintf(b, "// %s is the payload for the %q aspect on %s.\n", typeName, aspect.Name, base)
	}
	if aspect.PayloadSchema == nil {
		// No schema declared — emit an opaque alias so callers can
		// still reference the type by name.
		imports["encoding/json"] = struct{}{}
		fmt.Fprintf(b, "type %s = json.RawMessage\n\n", typeName)
		return
	}
	emitGoType(b, typeName, aspect.PayloadSchema, imports, 0)
	b.WriteString("\n")
}

// emitGoType writes a Go type declaration named typeName for the given
// schema. Nested object schemas are emitted inline as anonymous structs
// so the output is one named type per aspect.
func emitGoType(b *strings.Builder, typeName string, s *schema.JSONSchema, imports map[string]struct{}, depth int) {
	if depth > 0 {
		// Should not happen in the top-level call; reserved for future
		// extraction of named subtypes.
		fmt.Fprintf(b, "// %s nested\n", typeName)
	}
	switch s.Type {
	case "object", "":
		fmt.Fprintf(b, "type %s struct {\n", typeName)
		emitGoObjectFields(b, s, imports, 1)
		b.WriteString("}\n")
	case "array":
		inner := goLeafType(s.Items, imports)
		fmt.Fprintf(b, "type %s []%s\n", typeName, inner)
	default:
		fmt.Fprintf(b, "type %s %s\n", typeName, goLeafType(s, imports))
	}
}

// emitGoObjectFields writes one Go struct field per property.
func emitGoObjectFields(b *strings.Builder, s *schema.JSONSchema, imports map[string]struct{}, indent int) {
	required := map[string]struct{}{}
	for _, r := range s.Required {
		required[r] = struct{}{}
	}
	props := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		props = append(props, k)
	}
	sort.Strings(props)

	ind := strings.Repeat("\t", indent)
	for _, name := range props {
		sub := s.Properties[name]
		fieldName := toPascal(name)
		typ := goFieldType(sub, imports, indent)
		_, req := required[name]
		jsonTag := name
		if !req {
			jsonTag = name + ",omitempty"
			// json.Marshal can only honor omitempty on a struct field
			// when the value is nilable (pointer / slice / map /
			// interface). Wrap inline struct fields in a pointer so
			// the tag has effect.
			if strings.HasPrefix(typ, "struct {") {
				typ = "*" + typ
			}
		}
		if sub != nil && sub.Description != "" {
			fmt.Fprintf(b, "%s// %s\n", ind, sub.Description)
		}
		fmt.Fprintf(b, "%s%s %s `json:%q`\n", ind, fieldName, typ, jsonTag)
	}
	// additionalProperties: nil or true → allow unknown fields via
	// a final json.RawMessage catch-all? Skipped: callers can layer
	// json.Decoder.DisallowUnknownFields when strictness matters and
	// the registry already records the contract.
}

// goFieldType returns the Go type expression for a property.
func goFieldType(s *schema.JSONSchema, imports map[string]struct{}, indent int) string {
	if s == nil {
		imports["encoding/json"] = struct{}{}
		return "json.RawMessage"
	}
	switch s.Type {
	case "string":
		return "string"
	case "number":
		return "float64"
	case "integer":
		return "int64"
	case "boolean":
		return "bool"
	case "null":
		return "any"
	case "array":
		return "[]" + goFieldType(s.Items, imports, indent)
	case "object":
		// Inline nested struct.
		var nested strings.Builder
		nested.WriteString("struct {\n")
		emitGoObjectFields(&nested, s, imports, indent+1)
		nested.WriteString(strings.Repeat("\t", indent))
		nested.WriteByte('}')
		return nested.String()
	default:
		imports["encoding/json"] = struct{}{}
		return "json.RawMessage"
	}
}

// goLeafType returns a non-struct Go type for use in type aliases and
// array element positions.
func goLeafType(s *schema.JSONSchema, imports map[string]struct{}) string {
	if s == nil {
		imports["encoding/json"] = struct{}{}
		return "json.RawMessage"
	}
	switch s.Type {
	case "string":
		return "string"
	case "number":
		return "float64"
	case "integer":
		return "int64"
	case "boolean":
		return "bool"
	default:
		imports["encoding/json"] = struct{}{}
		return "json.RawMessage"
	}
}
