package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/frankbardon/parsec/schema"
)

// TSGenerator emits a single self-contained TypeScript file.
type TSGenerator struct{}

// Name implements Generator.
func (TSGenerator) Name() string { return "ts" }

// Generate implements Generator.
func (g TSGenerator) Generate(snap schema.Snapshot, opts Options) ([]byte, error) {
	var buf bytes.Buffer
	if opts.Header != "" {
		buf.WriteString(opts.Header)
		if !strings.HasSuffix(opts.Header, "\n") {
			buf.WriteByte('\n')
		}
	}
	fmt.Fprintln(&buf, "// Code generated by parsec-gen. DO NOT EDIT.")
	fmt.Fprintln(&buf, "")

	for _, p := range sortedPatterns(snap) {
		emitTSPattern(&buf, p)
	}
	return buf.Bytes(), nil
}

func emitTSPattern(b *bytes.Buffer, p schema.ChannelPattern) {
	base := patternIdent(p.Pattern)
	fmt.Fprintf(b, "/** Registered channel pattern. */\n")
	fmt.Fprintf(b, "export const %sPattern = %q as const;\n\n", base, p.Pattern)

	placeholders := patternPlaceholders(p.Pattern)
	if len(placeholders) > 0 {
		emitTSChannelHelper(b, base, p.Pattern, placeholders)
	}

	for _, aspectName := range sortedAspectNames(p.Aspects) {
		aspect := p.Aspects[aspectName]
		emitTSAspectPayload(b, base, aspect)
	}
}

func emitTSChannelHelper(b *bytes.Buffer, base, pattern string, phs []placeholder) {
	args := make([]string, 0, len(phs))
	for _, ph := range phs {
		if ph.Trailing {
			args = append(args, ph.Name+": string[]")
			continue
		}
		args = append(args, ph.Name+": string")
	}

	fmt.Fprintf(b, "/** Build a concrete channel name from %s. */\n", pattern)
	fmt.Fprintf(b, "export function %sChannel(%s): string {\n", lcFirst(base), strings.Join(args, ", "))
	fmt.Fprintf(b, "  return %s;\n", tsChannelExpr(pattern))
	b.WriteString("}\n\n")
}

func tsChannelExpr(pattern string) string {
	toks := patternTokens(pattern)
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		switch {
		case t.Literal != "":
			parts = append(parts, fmt.Sprintf("%q", t.Literal))
		case t.PlaceholderName == "rest":
			parts = append(parts, `rest.join(".")`)
		default:
			parts = append(parts, t.PlaceholderName)
		}
	}
	if len(parts) == 0 {
		return `""`
	}
	return strings.Join(parts, " + ")
}

func emitTSAspectPayload(b *bytes.Buffer, base string, aspect schema.Aspect) {
	typeName := base + aspectIdent(aspect.Name)
	if aspect.Description != "" {
		fmt.Fprintf(b, "/** %s */\n", aspect.Description)
	} else {
		fmt.Fprintf(b, "/** Payload for the %q aspect on %s. */\n", aspect.Name, base)
	}
	if aspect.PayloadSchema == nil {
		fmt.Fprintf(b, "export type %s = unknown;\n\n", typeName)
		return
	}
	emitTSType(b, typeName, aspect.PayloadSchema)
	b.WriteString("\n")
}

func emitTSType(b *bytes.Buffer, typeName string, s *schema.JSONSchema) {
	switch s.Type {
	case "object", "":
		fmt.Fprintf(b, "export interface %s {\n", typeName)
		emitTSObjectFields(b, s, 1)
		b.WriteString("}\n")
	case "array":
		fmt.Fprintf(b, "export type %s = %s[];\n", typeName, tsLeafType(s.Items))
	default:
		fmt.Fprintf(b, "export type %s = %s;\n", typeName, tsLeafType(s))
	}
}

func emitTSObjectFields(b *bytes.Buffer, s *schema.JSONSchema, indent int) {
	required := map[string]struct{}{}
	for _, r := range s.Required {
		required[r] = struct{}{}
	}
	props := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		props = append(props, k)
	}
	sort.Strings(props)

	ind := strings.Repeat("  ", indent)
	for _, name := range props {
		sub := s.Properties[name]
		_, req := required[name]
		opt := ""
		if !req {
			opt = "?"
		}
		typ := tsFieldType(sub, indent)
		if sub != nil && sub.Description != "" {
			fmt.Fprintf(b, "%s/** %s */\n", ind, sub.Description)
		}
		fmt.Fprintf(b, "%s%s%s: %s;\n", ind, tsPropName(name), opt, typ)
	}
}

func tsFieldType(s *schema.JSONSchema, indent int) string {
	if s == nil {
		return "unknown"
	}
	switch s.Type {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		return tsFieldType(s.Items, indent) + "[]"
	case "object":
		var nested bytes.Buffer
		nested.WriteString("{\n")
		emitTSObjectFields(&nested, s, indent+1)
		nested.WriteString(strings.Repeat("  ", indent))
		nested.WriteByte('}')
		return nested.String()
	default:
		return "unknown"
	}
}

func tsLeafType(s *schema.JSONSchema) string {
	if s == nil {
		return "unknown"
	}
	switch s.Type {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	default:
		return "unknown"
	}
}

// tsPropName wraps property names that aren't valid bare identifiers
// in quotes. We accept the common case (letters, digits, underscore,
// starts with non-digit) bare.
func tsPropName(name string) string {
	if name == "" {
		return `""`
	}
	for i, r := range name {
		isLetter := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || r == '$'
		isDigit := r >= '0' && r <= '9'
		if i == 0 && !isLetter {
			return fmt.Sprintf("%q", name)
		}
		if !isLetter && !isDigit {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = toLowerRune(r[0])
	return string(r)
}

func toLowerRune(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}
